# .github/workflows/deploy.yaml
name: Deploy Node.js App to K3s

on:
  push:
    branches:
      - main # Trigger on every push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The GitHub-hosted runner that will execute the steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Retrieves your code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Configures Docker Buildx

      - name: Login to GitHub Container Registry
        # This 'uses' was misaligned. It must be indented under '- name: Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Uses the automatically provided GitHub token

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (current directory)
          push: true
          # Image tag: ghcr.io/your_org/your_repo:commit_sha
          # This 'tags' line was causing the error. It was likely a remnant or misformatted.
          # The correct 'tags' line is below it.
          tags: ghcr.io/rouatest21/my-nodejs-k8s-app:${{ github.sha }} # <--- THIS IS THE CORRECTED LINE
          # You can also add a 'latest' tag if you want
          # tags: |
          #   ghcr.io/rouatest21/my-nodejs-k8s-app:${{ github.sha }}
          #   ghcr.io/rouatest21/my-nodejs-k8s-app:latest

      # This '- name: Set up Kubeconfig for K3s' was misaligned.
      # It must be at the same indentation level as other '- name:' steps.
      - name: Set up Kubeconfig for K3s
        run: |
          # Écriture du secret dans un fichier temporaire pour inspection
          echo "${{ secrets.KUBECONFIG_BASE64_K3S }}" > /tmp/kubeconfig_b64.txt

          echo "--- Début du débogage Kubeconfig ---"
          echo "Contenu brut du secret (avec caractères non imprimables):"
          cat -v /tmp/kubeconfig_b64.txt
          echo "Longueur du secret:"
          wc -c /tmp/kubeconfig_b64.txt
          echo "--- Tentative de décodage ---"

          # Tente de décoder le secret du fichier temporaire
          base64 -d /tmp/kubeconfig_b64.txt > ~/.kube/config

          echo "--- Fin du débogage Kubeconfig ---"

          mkdir -p ~/.kube # Assurez-vous que le répertoire existe au cas où
          # chmod 600 ~/.kube/config # Permet de régler les permissions une fois le fichier créé
          chmod 600 ~/.kube/config # Déplacez cette ligne ici pour s'assurer que le fichier existe avant le chmod

      - name: Deploy MongoDB to K3s
        run: |
          kubectl apply -f k8s/mongodb-deployment.yaml
          kubectl apply -f k8s/mongodb-service.yaml
          # Wait for the MongoDB deployment to be ready before proceeding
          kubectl rollout status deployment/mongodb-deployment --timeout=5m 

      - name: Deploy Node.js App to K3s
        run: |
          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/app-service.yaml
          # Wait for the application deployment to be ready
          kubectl rollout status deployment/nodejs-app-deployment --timeout=5m

