# .github/workflows/deploy.yaml
name: Deploy Node.js App to K3s

on:
  push:
    branches:
      - main # Trigger on every push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The GitHub-hosted runner that will execute the steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Retrieves your code from the repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Configures Docker Buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Uses the automatically provided GitHub token

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (current directory)
          push: true
tags          # Image tag: ghcr.io/your_org/your_repo:commit_sha
          tags: ghcr.io/rouatest21/my-nodejs-k8s-app:${{ github.sha }} # <--- REPLACE THIS LINE WITH YOUR REPO
          # You can also add a 'latest' tag if you want
          # tags: |
          #   ghcr.io/rouatest21/my-nodejs-k8s-app:${{ github.sha }}
          #   ghcr.io/rouatest21/my-nodejs-k8s-app:latest

      - name: Set up Kubeconfig for K3s
        run: |
          mkdir -p ~/.kube
          # Decode the base64 secret containing your kubeconfig and write it to ~/.kube/config
          # This secret must contain the content of your /etc/rancher/k3s/k3s.yaml
    /      # with 127.0.0.1 REPLACED by your VM Master's IP (e.g., 192.168.1.15)
          echo "${{ secrets.KUBECONFIG_BASE64_K3S }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config # Set correct permissions

      - name: Deploy MongoDB to K3s
        run: |
          kubectl apply -f k8s/mongodb-deployment.yaml
          kubectl apply -f k8s/mongodb-service.yaml
          # Wait for the MongoDB deployment to be ready before proceeding
          kubectl rollout status deployment/mongodb-deployment --timeout=5m 

      - name: Deploy Node.js App to K3s
        run: |
          kubectl apply -f k8s/app-deployment.yaml
          kubectl apply -f k8s/app-service.yaml
          # Wait for the application deployment to be ready
          kubectl rollout status deployment/nodejs-app-deployment --timeout=5m
